name:                hamocrm
version:             0.1.0.0
github:              "nlv/hamocrm"
license:             BSD3
author:              "Leon Nikitin"
maintainer:          "nlvomsk@gmail.com"
copyright:           "Leon Nikitin"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nlv/hamocrm#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - vector
  - conduit
  - conduit-extra
  - http-types
  - http-client
  - http-client-tls
  - http-conduit
  - aeson
  - time
  - text
  - lens
  - vector
  - servant
  - servant-server

executables:
  hamocrm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamocrm

tests:
  hamocrm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hamocrm
